### PR TITLE
Testing on android

### PR DESCRIPTION
**Pull request by Mysticgwen**
Am I able to create pull request, download files, and open command line via HTML editor on phone since new windows laptop isn't recognizing windows git downloads and/or git desktop

### CODE REVIEW

**Comment by ghost** [comment]
Squashed and merged it to declutter the commits

**Review by ghost — COMMENTED** [review]
looks fine

**Comment by Mysticgwen** [comment]
https://youtu.be/8-bgiiTxhzM?si=EjzFsvEYIgl0_Skb

**Comment by Mysticgwen** [comment]
I'll be here for emotional support 😆

**Pull request closed without merging**
